admin/src/web/controllers/contacts.py
from typing import Dict, List

from flask import (
    Blueprint,
    abort,
    current_app,
    render_template,
    redirect,
    url_for,
    request,
    flash,
)

from src.core.contacts import (
    count_contacts,
    get_consulta_by_id,
    paginar_consultas,
    modificar_consulta,
    eliminar_consulta,
    validate_filter_params,
)
from src.core.contacts.contacts import Contact
from src.web.handlers.auth import login_required, is_admin, permission_required
from src.web.validators.contact_validations import validate_update_contact


bp = Blueprint("contacts", __name__, url_prefix="/contacts")


@bp.get("/")
@bp.get("/<int:page>")
@login_required
@permission_required("contact_index")
def index(page: int = 1):
    """
    Muestra la lista de consultas paginadas.

    Args:
        page (int): Número de la página.

    Returns:
        str: Renderización de la plantilla 'contacts/index.html'.
    """
    if not isinstance(page, int):
        abort(400)

    if page == 0:
        flash("No existe esa página, reintente", "error")
        return redirect(url_for("contacts.index"))

    start_date: str = request.args.get("start_date", "")
    end_date: str = request.args.get("end_date", "")
    estado: str = request.args.get("estado", "")
    order: str = request.args.get("order", "")
    params: Dict[str, str] = {
        "start_date": start_date,
        "end_date": end_date,
        "estado": estado,
        "order": order,
    }

    messages: List[str] = validate_filter_params(params)
    if messages:
        for error in messages:
            flash(error, "error")
        return redirect(url_for("contacts.index", _external=True))

    total_contacts = count_contacts(
        start_date=start_date, end_date=end_date, estado=estado.lower()
    )
    max_elements = current_app.config["MAX_ELEMENTS_ON_PAGE"]
    total_pages = (total_contacts + max_elements - 1) // max_elements

    if total_pages != 0 and page > total_pages:
        flash(f"La página {page} no existe. Mostrando la última página.", "error")
        return redirect(url_for("contacts.index", page=total_pages, **params))

    contacts_paginated = paginar_consultas(
        start_date=start_date,
        end_date=end_date,
        estado=estado.lower(),
        order=order,
        page=page,
    )
    next_page = (
        url_for("contacts.index", page=contacts_paginated.next_num, **params)
        if contacts_paginated.has_next
        else None
    )
    prev_page = (
        url_for("contacts.index", page=contacts_paginated.prev_num, **params)
        if contacts_paginated.has_prev
        else None
    )

    return render_template(
        "contacts/index.html",
        consultas=contacts_paginated,
        next_page=next_page,
        prev_page=prev_page,
        params=params,
    )


@bp.get("/show/<int:consulta_id>")
@login_required
@is_admin
def show(consulta_id: int):
    """
    Muestra el detalle de una consulta específica.

    Args:
        consulta_id (int): ID de la consulta.

    Returns:
        str: Renderización de la plantilla 'contacts/show.html'.
    """

    consulta = get_consulta_by_id(consulta_id)
    if consulta is not None:
        return render_template("contacts/show.html", consulta=consulta)

    flash("Consulta no encontrada", "error")
    return redirect(url_for("contacts.index"))


@bp.get("/actualizar/<int:consulta_id>")
@login_required
@permission_required("contact_update")
def show_update(consulta_id: int):
    """
    Muestra el formulario para actualizar una consulta.

    Args:
        consulta_id (int): ID de la consulta.

    Returns:
        str: Renderización de la plantilla 'contacts/create_edit.html'.
    """
    if not isinstance(consulta_id, int):
        abort(400)
    consulta: Contact = get_consulta_by_id(consulta_id)
    if consulta is None:
        flash("No se encontró la consulta", "error")
        return redirect(url_for("contacts.index"))
    params: Dict[str, str] = {
        "full_name": consulta.full_name,
        "email": consulta.email,
        "message": consulta.message,
        "state": consulta.state,
        "date": consulta.creation_date,
        "comment": consulta.comment if consulta.comment is not None else "",
    }

    return render_template(
        "contacts/create_edit.html", consulta_id=consulta_id, params=params
    )


@bp.post("/actualizar/<int:consulta_id>/update")
@login_required
@is_admin
def update(consulta_id: int):
    """
    Actualiza una consulta existente.

    Args:
        consulta_id (int): ID de la consulta.

    Returns:
        werkzeug.wrappers.Response: Redirección a la página principal de consultas.
    """
    if not isinstance(consulta_id, int):
        abort(400)
    consulta: Contact = get_consulta_by_id(consulta_id=consulta_id)
    if consulta is None:
        flash("No se encontró la consulta", "error")
        return redirect(url_for("contacts.index"))
    params = request.form.to_dict()
    estado = params.get("state")
    comentario = params.get("comment")
    new_params: Dict[str, str] = {
        "full_name": consulta.full_name,
        "email": consulta.email,
        "message": consulta.message,
        "state": consulta.state,
        "date": consulta.creation_date,
        "comment": comentario,
    }
    # Validaciones
    messages = validate_update_contact(params)
    if messages:
        for error in messages:
            flash(error, "error")
        return render_template(
            "contacts/create_edit.html", consulta_id=consulta_id, params=new_params
        )

    modificar_consulta(consulta_id, estado, comentario)
    flash("Consulta actualizada correctamente", "success")

    return redirect(url_for("contacts.index"))


@bp.post("/delete/")
@login_required
@is_admin
def delete():
    """
    Elimina una consulta.

    Returns:
        werkzeug.wrappers.Response: Redirección a la página principal de consultas.
    """
    params = request.form
    consulta_id: str = params.get("contact_id", "")

    if not isinstance(consulta_id, str):
        flash("No se proporcionó correctamente la información para eliminar.", "error")
        return redirect(url_for("contacts.index"))
    if not consulta_id.isdigit():
        flash("No se proporcionó correctamente la información para eliminar.", "error")
        return redirect(url_for("contacts.index"))
    id_consulta: int = int(consulta_id)
    try:
        eliminar_consulta(id_consulta)
        flash("Consulta eliminada correctamente", "success")
    except ValueError:
        flash("No se proporcionó correctamente la información para eliminar.", "error")

    return redirect(url_for("contacts.index"))

admin/src/web/templates/contacts/create_edit.html
{% extends "templates_base/layout.html" %}

{% block title %} Contactos {% endblock %}

{% block navbar %}
    {% include "templates_base/navbar.html" %}
{% endblock %}

{% block content %}
<h2>Formulario de Contacto</h2>

    <form method="POST" action="{{ url_for('contacts.update', consulta_id=consulta_id) }}">
        <p class="text-muted" style="text-shadow: 1px 1px 2px gray;">(*) espacios obligatorios</p>
        <div class="mb-3">
            <label for="full_name" class="form-label">Nombre Completo </label>
            <input type="text" class="form-control" id="full_name"
            name="full_name" value="{{ params.get('full_name', '') }}" disabled>
        </div>

        <div class="mb-3">
            <label for="email" class="form-label">Email </label>
            <input type="email" class="form-control" id="email"
            name="email" value="{{ params.get('email', '') }}" disabled>
        </div>

        <div class="mb-3">
            <label for="date" class="form-label">Fecha de la consulta</label>
            <input type="date" class="form-control" id="date" name="date"
            value="{{ params.get('date', '') }}" disabled>
        </div>

        <div class="mb-3">
            <label for="message" class="form-label">Mensaje </label>
            <textarea class="form-control" id="message" name="message" disabled>{{ params.get('message', '') }}</textarea>
        </div>

        <div class="mb-3">
            <label for="state" class="form-label">Estado (*)</label>
            <select class="form-control" id="state" name="state" required>
                <option value="" {% if params.get('state') == '' %}selected{% endif %} >---</option>
                <option value="pendiente" {% if params.get('state') == 'pendiente' %}selected{% endif %}>Pendiente</option>
                <option value="en proceso" {% if params.get('state') == 'en proceso' %}selected{% endif %}>En Proceso</option>
                <option value="terminado" {% if params.get('state') == 'terminado' %}selected{% endif %}>Terminado</option>
            </select>
        </div>

        <div class="mb-3">
            <label for="coment" class="form-label">Comentario</label>
            <textarea class="form-control" id="comment" name="comment">{{ params.get('comment', '') }}</textarea>
        </div>
        <button type="reset" class="btn btn-secondary">Limpiar</button>
        <button type="submit" class="btn btn-primary">Actualizar</button>
    </form>

{% endblock %}
{% block volver %}
<br>
    <a class="btn btn-danger" href="{{ url_for('contacts.show', consulta_id = consulta_id) }}">◄ Volver</a>
{% endblock %}

admin/src/web/templates/contacts/index.html
{% extends "templates_base/layout.html" %}

{% block title %}Listado de Consultas{% endblock %}

{% block navbar %}
    {% include "templates_base/navbar.html" %}
{% endblock %}

{% block content %}
    <h2>Panel de consultas de portal público</h2>
    <form id="filtros" action="{{ url_for('contacts.index') }}" method="GET">
        <div class="row" style="justify-content: center;">
            <div class="col">
                <label for="start_date" class="form-label">Fecha inicio</label>
                <input 
                    type="date" 
                    class="form-control" 
                    id="start_date" 
                    name="start_date" 
                    value="{{ params.get('start_date', '') }}" 
                    onchange="updateEndDateMin()"
                >
            </div>
            <div class="col">
                <label for="end_date" class="form-label">Fecha fin</label>
                <input 
                    type="date" 
                    class="form-control" 
                    id="end_date" 
                    name="end_date" 
                    value="{{ params.get('end_date', '') }}" 
                    onchange="updateStartDateMax()"
                >
            </div>
            
            <div class="col">
                <label for="estado" class="form-label">Estado</label>
                <select class="form-control" id="estado" name="estado">
                    <option value="">Todos</option>
                    <option value="PENDIENTE" {% if params.get("estado", '') == 'PENDIENTE' %}selected{% endif %}>Pendiente</option>
                    <option value="EN PROCESO" {% if params.get("estado", "") == 'EN PROCESO' %}selected{% endif %}>En Proceso</option>
                    <option value="TERMINADO" {% if params.get("estado", "") == 'TERMINADO' %}selected{% endif %}>Terminado</option>
                </select>
            </div>
            <div class="col">
                
                <label for="order" class="form-label">Seleccione un orden</label>
                <select name="order" id="order" class="form-select">
                    <option value="">--Orden--</option>
                    <option value="newer" {% if params.get('order', '')=='newer' %}selected{% endif %}>Más recientes</option>
                    <option value="older" {% if params.get('order', '')=='older' %}selected{% endif %}>Más viejos</option>
                </select>
            </div>
        </div>
        <div class="row" style="justify-content: center;">
            
            
            <div class="col text-end">
                <hr>
                <div>
                    <a class="btn btn-secondary me-2" href="{{ url_for('contacts.index') }}">Limpiar filtros</a>
                    <button type="submit" class="btn btn-primary">Filtrar</button>
                </div>
            </div>
        </div>
    </form>
    

    
    <div class="row mt-4">
        {% for consulta in consultas %}
        <div class="col-md-4 mb-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-truncate">{{ consulta.full_name }}</h5>
                    <p class="card-text text-truncate">
                        <strong>Fecha:</strong> {{ consulta.get_readable_creation_date }}<br>
                        <strong>Email:</strong> {{ consulta.email }}<br>
                        <strong>Estado:</strong> {{ consulta.state.capitalize() }}<br>
                        {% if consulta.comment %}
                            <strong>Comentario:</strong>
                            <span class="text-truncate">{{ consulta.comment }}</span><br>
                        {% endif %}
                        <strong>Título:</strong>
                        <span class="text-truncate">{{ consulta.title }}</span><br>
                        <strong>Mensaje:</strong>
                        <span class="text-truncate">{{ consulta.message }}</span>
                    </p>
                    <div class="d-flex justify-content-center" style="gap: 3px;">
                        <a class="btn btn-info" href="{{ url_for('contacts.show', consulta_id=consulta.id) }}">Ver detalles</a>
                        <button 
                            type="button" 
                            class="btn btn-danger" 
                            onclick="showDeleteModal({{ consulta.id }})">
                            Eliminar
                        </button>
                    </div>
                </div>
            </div>
        </div>
        
            
        {% endfor %}
        {% if consultas.items|length == 0 %}
            <div class="col-12 text-center my-4">
                <div class="alert alert-warning py-4">
                    <h5>No se encontraron resultados</h5>
                    <p class="mb-0">No se encontraron consultas registradas con esos criterios.</p>
                </div>
            </div>
        {% endif %}
    </div>
    {% if consultas.items|length != 0 %}

    <nav aria-label="Page navigation" class="mt-4">
        <ul class="pagination justify-content-center">
            {% if consultas.has_prev %}
            <li class="page-item">
                <a class="page-link" href="{{ prev_page }}" aria-label="Anterior">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% endif %}
            {% if consultas.items|length == 0 %}
                <li class="page-item disabled"><a class="page-link" href="#">Página 0 de 0</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="#">Página {{ consultas.page }} de {{ consultas.pages }}</a></li>
            {% endif %}
            {% if consultas.has_next %}
            <li class="page-item">
                <a class="page-link" href="{{ next_page }}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}

    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Confirmar eliminación</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
                    </div>
                    <div class="modal-body">
                        <p>¿Está seguro que desea eliminar este contacto?</p>
                        
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        <form method="POST" action="{{ url_for('contacts.delete') }}">
                            <input type="hidden" name="contact_id" id="deleteContactId" value="">
                            <button type="submit" class="btn btn-danger">Eliminar</button>
                        </form>
                    </div>
                
            </div>
        </div>
    </div>

<script>
    function showDeleteModal(contactId) {
        document.getElementById('deleteContactId').value = contactId;
        const deleteModal = new bootstrap.Modal(document.getElementById('deleteModal'));
        deleteModal.show();
    }

    
</script>
<script>
    function updateEndDateMin() {
        const startDate = document.getElementById('start_date').value;
        const endDateInput = document.getElementById('end_date');

        if (startDate) {
            endDateInput.min = startDate; // Establece la fecha mínima en el segundo input
        }
    }

    function updateStartDateMax() {
        const endDate = document.getElementById('end_date').value;
        const startDateInput = document.getElementById('start_date');

        if (endDate) {
            startDateInput.max = endDate; // Establece la fecha máxima en el primer input
        }
    }

    // Inicializa las restricciones al cargar la página (opcional)
    document.addEventListener('DOMContentLoaded', () => {
        updateEndDateMin();
        updateStartDateMax();
    });
</script>
{% endblock %}

{% block volver %}
<br>
    <a class="btn btn-danger" href="{{ url_for('auth.home') }}">◄ Volver</a>
{% endblock %}

admin/src/web/templates/contacts/show.html
{% extends "templates_base/layout.html" %}

{% block title %}Detalle de Consulta{% endblock %}

{% block navbar %}
    {% include "templates_base/navbar.html" %}
{% endblock %}

{% block content %}
<div class="row mt-4">
    <div class="col-md-8 offset-md-2">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{ consulta.full_name }}</h5>
                <p class="card-text">
                    <strong>Fecha:</strong> {{ consulta.get_readable_creation_date }}<br>
                    <strong>Email:</strong> {{ consulta.email }}<br>
                    <strong>Titulo:</strong> {{ consulta.title }}<br>
                    <strong>Estado:</strong> {{ consulta.state }}<br>
                    <strong>Comentario:</strong> {{ consulta.coment }}<br>
                    <strong>Mensaje:</strong> {{ consulta.message }}
                </p>
                <div class="d-flex justify-content-center" style="gap: 3px;">
                    <a class="btn btn-warning" href="{{ url_for('contacts.show_update', consulta_id=consulta.id) }}">Editar</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block volver %}
<br>
    <a class="btn btn-danger" href="{{ url_for('contacts.index') }}">◄ Volver</a>
{% endblock %}