admin/src/web/controllers/payments.py
from typing import List

from flask import render_template, Blueprint, redirect, url_for, request, flash

from src.core import payments
from src.core.payments import order_and_filter_payments, delete_payment_by_id
from src.core.payments.payments import Payment
from src.core.team import get_employee, get_employees, get_active_employees
from src.web.handlers.exceptions import PaymentNotFoundException
from src.web.handlers.auth import login_required, is_admin


bp = Blueprint("payments", __name__, url_prefix="/pagos")


@bp.post("/create_payment")
@login_required
@is_admin
def create_payment():
    """
    Crea un nuevo pago en el sistema.

    Esta función recibe los datos del formulario de creación de pago, validar que
    los parámetros sean correctos y, en caso de serlo, crea un nuevo pago en la
    base de datos. Si ocurre un error durante la validación o la creación del
    pago, se muestra un mensaje de error al usuario. Si el pago se genera correctamente,
    se redirige a la página de dashboard de pagos con un mensaje de éxito.

    Parámetros:
    - `beneficiary_id`: ID del beneficiario del pago.
    - `payment_type`: Tipo de pago (por ejemplo, 'Honorarios').
    - `payment_date`: Fecha del pago.
    - `amount`: Monto del pago.
    - `description`: Descripción del pago.

    Redirecciones:
    - Si el pago se crea correctamente: `payments.dashboard`.
    - Si ocurre un error: `payments.new_payment`.

    Mensajes de flash:
    - Si ocurre un error durante la validación o la creación: Muestra el error en pantalla.
    - Si el pago se crea con éxito: Muestra un mensaje de éxito.

    Excepciones:
    - Si alguno de los parámetros es incorrecto o no válido, se muestra un mensaje de error.
    """
    beneficiary_id = request.form.get("beneficiary_id")
    payment_type = request.form.get("payment_type")
    if beneficiary_id == "" or payment_type != "Honorarios":
        beneficiary_id = None
    payment_date = request.form.get("payment_date")
    amount = request.form.get("amount")
    description = request.form.get("description")
    messages: List[str] = []

    messages.extend(
        payments.check_create_params(
            beneficiary_id=beneficiary_id,
            payment_date=payment_date,
            amount=amount,
            description=description,
            payment_type=payment_type,
        )
    )
    if len(messages) > 0:
        for message in messages:
            flash(message, "error")
        return redirect(url_for("payments.new_payment"))

    payments.create_payment(
        beneficiary_id=beneficiary_id,
        payment_date=payment_date,
        payment_type=payment_type,
        amount=amount,
        description=description,
    )
    flash("Pago creado correctamente", "success")

    return redirect(url_for("payments.dashboard"))


@bp.get("/create")
@login_required
@is_admin
def new_payment():
    """Renderiza el formulario para crear un nuevo pago."""
    type_payment = request.args.get("type")
    employees = get_active_employees()

    return render_template("payments/form.html", employees=employees, type=type_payment)


@bp.get("/dashboard")
@login_required
@is_admin
def dashboard():
    """Renderiza la vista de pagos."""
    start_date = request.args.get("start_date")
    end_date = request.args.get("end_date")
    search_value = request.args.get("search_value")
    order = request.args.get("order", "desc")
    page = request.args.get("page", 1, type=int)
    payments_list, pagination, beneficiarys = order_and_filter_payments(
        page, order, search_value, start_date, end_date
    )

    return render_template(
        "payments/index.html",
        payments=payments_list,
        beneficiarys=beneficiarys,
        pagination=pagination,
        search_value=search_value,
        order=order,
        start_date=start_date,
        end_date=end_date,
    )


@bp.get("/pago/<int:payment_id>")
@login_required
@is_admin
def show_payment(payment_id):
    """Renderiza la vista de un pago en específico."""
    payment = Payment.query.get_or_404(payment_id)
    if payment.payment_type == "Honorarios":
        employee = get_employee(payment.beneficiary_id)
        if employee:
            return render_template(
                "payments/show.html", payment=payment, employee=employee
            )
        else:
            flash("No se encontró al empleado del pago", "error")
            return redirect(url_for("payments.dashboard"))

    return render_template("payments/show.html", payment=payment)


@bp.post("/update")
@login_required
@is_admin
def update_payment():
    """Recibe los datos de un pago y los actualiza en la base de datos."""
    payment_id = request.form.get("payment_id")
    beneficiary_id = request.form.get("beneficiary_id")
    payment_date = request.form.get("payment_date")
    payment_type = request.form.get("payment_type")
    amount = request.form.get("amount")
    description = request.form.get("description")
    messages = []

    messages.extend(
        payments.update_payment(
            payment_id,
            beneficiary_id=beneficiary_id,
            payment_date=payment_date,
            payment_type=payment_type,
            amount=amount,
            description=description,
        )
    )

    if messages:
        for message in messages:
            flash(message, "error")
        return redirect(url_for("payments.dashboard"))

    flash("Pago actualizado correctamente", "success")

    return redirect(url_for("payments.dashboard"))


@bp.get("/pago/<int:payment_id>/edit")
@login_required
@is_admin
def edit_payment(payment_id):
    """Renderiza el formulario para editar un pago."""
    payment = payments.get_payment_by_id(payment_id)
    if payment is None:
        flash("No se encontró el pago", "error")
        return redirect(url_for("payments.dashboard"))
    type_payment = (
        request.args.get("type") if request.args.get("type") else payment.payment_type
    )
    employees = get_employees()
    if payment.payment_type == "Honorarios":
        employee_act = get_employee(payment.beneficiary_id)
        if employee_act not in employees:
            employees.append(employee_act)

    return render_template(
        "payments/form.html", payment=payment, employees=employees, type=type_payment
    )


@bp.post("/delete")
@login_required
@is_admin
def delete_payment():
    """Recibe el id de un pago y lo elimina de la base de datos."""
    payment_id = request.form.get("payment_id")
    try:
        delete_payment_by_id(payment_id)
        flash("Pago eliminado correctamente", "success")
    except PaymentNotFoundException:
        flash("No se pudo eliminar el pago", "error")

        return redirect(url_for("payments.dashboard"))

    return redirect(url_for("payments.dashboard"))

admin/src/web/controllers/team_dashboard.py
from flask import Blueprint, render_template, request, redirect, url_for, flash

from src.core import team
from src.core.team import list_and_search_employees
from src.core.users import find_user_by_id
from src.web.handlers.auth import is_admin, login_required


bp = Blueprint("team_dashboard", __name__, url_prefix="/team_dashboard")


@bp.get("/")
@login_required
@is_admin
def index():
    """
    Renderiza la página del panel de control del equipo.

    Se obtienen los empleados y se aplica paginación, ordenamiento y búsqueda según los parámetros
    proporcionados por la solicitud.

    Returns:
        str: El HTML renderizado de la plantilla 'team/dashboard.html'.
    """

    page = request.args.get("page", 1, type=int)
    order_by = request.args.get("order", "name")
    order_direction = request.args.get("order_direction", "asc")
    search_by = request.args.get("search_by", "", type=str)
    search_value = request.args.get("search_value", "")
    profession_value = request.args.get("profesion_value", "")

    team.check_order_params(page, order_by, order_direction, search_by, search_value)

    employees, pagination = list_and_search_employees(
        page, search_value, search_by, order_by, order_direction
    )

    # busco aquellos empleados que tengan usuario
    alias_dict = {}

    for employee in employees:
        if employee.user_id:
            alias = find_user_by_id(employee.user_id).alias
            alias_dict[employee.user_id] = alias

    return render_template(
        "team/dashboard.html",
        page=page,
        employees=employees,
        pagination=pagination,
        order=order_by,
        order_direction=order_direction,
        search_value=search_value,
        profession_value=profession_value,
        search_by=search_by,
        alias_dict=alias_dict,
    )


@bp.post("/")
@login_required
@is_admin
def order():
    """
    Redirige a la página de panel de control del equipo con los parámetros de orden y búsqueda.

    Obtiene los parámetros de orden y búsqueda de la solicitud y redirige a la función de
    index con esos parámetros.

    Returns:
        Response: Redirección a la vista del panel de control del equipo.
    """
    page = request.form.get("page", 1, type=int)
    order_employees = request.form.get("order")
    order_direction = request.form.get("order_direction")
    search_by = request.form.get("search_by", "")
    search_value = (
        request.form.get("search_value", "")
        if search_by != "profesion"
        else request.form.get("profesion_value", "")
    )

    return redirect(
        url_for(
            "team_dashboard.index",
            page=page,
            order=order_employees,
            order_direction=order_direction,
            search_by=search_by,
            search_value=search_value,
        )
    )


@bp.post("/delete_employee")
@login_required
@is_admin
def delete():
    """
    Elimina (o desactiva) un empleado.

    Obtiene el ID del empleado desde el formulario y lo desactiva.
    Luego, muestra un mensaje de éxito y redirige a la vista del panel de control del equipo.

    Returns:
        Response: Redirección a la vista del panel de control del equipo.
    """
    employee_id = request.form.get("employee_id")
    if employee_id.isdigit():
        employee = team.toggle_active(employee_id)
        if employee:
            op = request.form.get("op")
            flash(f"Empleado {op} correctamente", "success")
        else:
            flash("No se ha podido realizar la operación", "error")
    else:
        flash("ID de empleado no válido", "error")

    return redirect(url_for("team_dashboard.index"))

admin/src/web/templates/payments/form.html
{% extends "templates_base/layout.html" %}

{% block title %} {{ 'Editar Pago' if payment else 'Crear Pago' }} {% endblock %}
{% block navbar%}
{% include "templates_base/navbar.html" %}
{% endblock %}

{% block content %}
<h1> {{ 'Editar Pago' if payment else 'Crear Pago' }} </h1>

<div class="container-fluid" style="width:'50%'">
    <form id="registro_form"
        action="{{ url_for('payments.update_payment') if payment else url_for('payments.create_payment') }}"
        method="POST">
        <div class="row" style="justify-content: center;">
            <input type="hidden" name="payment_id" value="{{ payment.id if payment else '' }}">
            <div class="col">
                <label for="payment_type" class="form-label">* Tipo de Pago</label>
                <select class="form-control" id="payment_type" name="payment_type" onchange="changeOptions()" required>
                    <option value="">Seleccione</option>
                    <option value="Honorarios" {% if type=='Honorarios' %} selected {% endif %}>
                        Honorarios</option>
                    <option value="Proveedor" {% if type=='Proveedor' %} selected {% endif %}>
                        Proveedor</option>
                    <option value="Gastos varios" {% if type=='Gastos varios' %} selected {%endif %}>Gastos Varios
                    </option>
                </select>
                <input type="hidden" name="type" value="{{ type }}">
            </div>
            <div class="col" id="beneficiary-container" style="display: none;">
                <label for="beneficiary_id" class="form-label">* Beneficiario: </label>
                <select class="form-control" id="beneficiary_id" name="beneficiary_id">
                    <option value="">Seleccione</option>
                    {% for beneficiary in employees %}
                    <option value="{{ beneficiary.id }}" {% if payment and payment.beneficiary_id==beneficiary.id %}
                        selected {% endif %}>{{ beneficiary.last_name }} {{ beneficiary.name }} DNI {{ beneficiary.dni
                        }} {% if payment and payment.beneficiary_id== beneficiary.id %}
                        *ACTUAL* {% endif %}</option>
                    {% endfor %}
                </select>

            </div>

            <div class="col">
                <label for="amount" class="form-label">* Monto $</label>
                <input type="text" class="form-control" id="amount" name="amount"
                    value="{{ payment.amount if payment else '' }}" required>
            </div>
        </div>
        <div class="row" style="justify-content: center;">
            <div class="col">
                <label for="payment_date" class="form-label">* Fecha de Pago</label>
                <input type="date" class="form-control" id="payment_date" name="payment_date"
                    value="{{ payment.payment_date.strftime('%Y-%m-%d') if payment else '' }}" required>
            </div>
        </div>
        <div class="row" style="justify-content: center;">
            <div class="col">
                <label for="description" class="form-label">Descripción</label>
                <textarea class="form-control" id="description" name="description" rows="3" maxlength="200"
                    style="resize: none;">{{ payment.description if payment else '' }}</textarea>
            </div>
        </div>
        <div class="row" style="justify-content: center; margin-top: 20px;">
            <div class="col text-end">
                <a class="btn btn-secondary" href="{{ url_for('payments.dashboard') }}">Cancelar</a>
                <button type="submit" class="btn btn-primary">{{ 'Actualizar Pago' if payment else 'Crear Pago'
                    }}</button>

            </div>
        </div>
    </form>
</div>
<script>

    document.addEventListener('DOMContentLoaded', function () {
        const paymentTypeElement = document.getElementById('payment_type');
        const beneficiaryContainer = document.getElementById('beneficiary-container');
        const beneficiarySelect = document.getElementById('beneficiary_id');

        function changeOptions() {
            const paymentType = paymentTypeElement.value;

            if (paymentType === 'Honorarios') {
                beneficiaryContainer.style.display = 'block';
                beneficiarySelect.setAttribute('required', true);
            } else {
                beneficiaryContainer.style.display = 'none';
                beneficiarySelect.value = '';
                beneficiarySelect.removeAttribute('required');
            }
        }

        // Ejecutar la función al cargar la página
        changeOptions();

        // Escuchar cambios en el select de payment_type
        paymentTypeElement.addEventListener('change', changeOptions);
    });

    document.getElementById('amount').addEventListener('input', function () {

        this.value = this.value.replace(/[^0-9.]/g, ''); // permito numeros y puntos
        // Se asegura de que solo haya un punto decimal
        if ((this.value.match(/\./g) || []).length > 1) {
            this.value = this.value.replace(/\.$/, ''); // si hay mas de un punto, saco el ultimo
        }
    });


    function goToPage(pageNumber) {
        const currentUrl = new URL(window.location.href);

        currentUrl.searchParams.set('page', pageNumber);

        currentUrl.searchParams.set('type', 'Honorarios');

        window.location.href = currentUrl.toString();
    }

    function resetPage() {
        window.location.href = "{{ url_for('payments.new_payment') }}";
    }

    const paymentDateInput = document.getElementById('payment_date');

    // Establecer el máximo de la fecha de pago como la fecha actual
    const currentDate = new Date().toISOString().split('T')[0];
    paymentDateInput.max = currentDate;


</script>
{% endblock %}

{% block volver %}
<br>
<a class="btn btn-danger" href="{{ url_for('payments.dashboard') }}">◄ Volver</a>
{% endblock %}

admin/src/web/templates/payments/index.html
{% extends "templates_base/layout.html" %}

{% block title %} Listado de Pagos {% endblock %}
{% block navbar%}
    {% include "templates_base/navbar.html" %}
{% endblock %}
{% block content %}

<h2>Panel de búsqueda de pagos</h2>
    <form id="filtros" action="{{ url_for('payments.dashboard') }}" method="GET">
        <div class="row" style="justify-content: center;">
            <div class="col">
                <label for="start_date" class="form-label">Fecha Inicio</label>
                <input 
                    type="date" 
                    class="form-control" 
                    id="start_date" 
                    name="start_date" 
                    placeholder="Fecha Inicio" 
                    value="{{ start_date }}"
                    onchange="updateEndDateMin()"
                >
            </div>
            <div class="col">
                <label for="end_date" class="form-label">Fecha Fin</label>
                <input 
                    type="date" 
                    class="form-control" 
                    id="end_date" 
                    name="end_date" 
                    placeholder="Fecha Fin"  
                    value="{{ end_date }}"
                    onchange="updateStartDateMax()"
                >
            </div>
            <div class="col">
                <label for="payment_type" class="form-label">Tipo de Pago</label>
                <select class="form-control" id="search_value" name="search_value">
                    <option value="">Todos</option>
                    <option value="Honorarios" {% if search_value == 'Honorarios'%}selected{%endif%}>Honorarios</option>
                    <option value="Proveedor" {% if search_value == 'Proveedor'%}selected{%endif%}>Proveedor</option>
                    <option value="Gastos Varios" {% if search_value == 'Gastos Varios'%}selected{%endif%}>Gastos Varios</option>
                </select>
            </div>
            <div class="col">
                
                <label class="form-label">Ordenar por fecha:</label>
                <select class="form-control" id="order" name="order">
                    <option value="" {% if order == '' %} selected {% endif %}>---</option>
                    <option value="asc" {% if order == 'asc' %} selected {% endif %}> Más viejos </option>
                    <option value="desc" {% if order == 'desc' %} selected {% endif %}>Más recientes</option>
                </select>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col">
                <div class="text-end">
                    <a class="btn btn-secondary" href="{{ url_for('payments.dashboard') }}">Limpiar Filtros</a>
                    <button type="submit" class="btn btn-primary" onclick="goToPage(1)">Filtrar</button>
                </div>
            </div>
        </div>
        <input type="hidden" name="page" id="page" value="{{ pagination.page }}">

    </form>
    
    
    <div class="row mt-4">
        {% for payment in payments %}
            <div class="col-md-4 mb-3">
                <div class="card h-100">
                    <div class="card-body">
                        
                        
                        <!-- Detalles del pago -->
                        {% if beneficiarys[payment.id] %}
                            <p class="card-text">
                                <strong>Beneficiario:</strong> {{ beneficiarys[payment.id] }}
                            </p>
                        {% endif %}
                        <p class="card-text">
                            <strong>Monto:</strong> ${{ payment.amount }}<br>
                            <strong>Fecha de pago:</strong> {{ payment.payment_date.strftime('%d/%m/%Y') }}<br>
                            <strong>Tipo de pago:</strong> {{ payment.payment_type }}
                        </p>
                        <!-- Botones dentro de un contenedor con espacio entre ellos -->
                        <div class="d-flex justify-content-center" style="gap: 3px;">
                            <!-- Botón Ver detalles -->
                            <a class="btn btn-info" href="{{ url_for('payments.show_payment', payment_id=payment.id) }}">Ver Detalles</a>
                            
                            <!-- Botón Eliminar -->
                            <button type="button" class="btn btn-danger" onclick="openDeletePaymentModal('{{ payment.id }}')">Eliminar</button>

                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        
        {% if payments|length == 0 %}
            <div class="col-12 text-center my-4">
                <div class="alert alert-warning py-4">
                    <h5>No se encontraron resultados</h5>
                    <p class="mb-0">No se encontraron pagos registrados con esos criterios.</p>
                </div>
            </div>
        {% endif %}
    </div>
    {% if payments|length != 0 %}
        <nav aria-label="Page navigation" class="mt-4">
            <ul class="pagination justify-content-center">
                {% if pagination.has_prev %}
                <li class="page-item">
                    <a class="page-link" href="#" onclick="goToPage('{{ pagination.prev_num }}')" aria-label="Anterior">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}
                <li class="page-item disabled"><a class="page-link" href="#">Página {{ pagination.page }} de {{
                        pagination.pages }}</a></li>
                {% if pagination.has_next %}
                <li class="page-item">
                    <a class="page-link" href="#" onclick="goToPage('{{ pagination.next_num }}')" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
    <!-- Modal -->
    <div class="modal fade" id="deletePaymentModal" tabindex="-1" aria-labelledby="deletePaymentModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content bg-white">
                <div class="modal-header">
                    <h5 class="modal-title" id="deletePaymentModalLabel">Eliminar Pago</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
                </div>
                <div class="modal-body">
                    ¿Está seguro de que desea eliminar este pago? Esta acción es <strong>irreversible</strong>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <form id="deletePaymentForm" method="POST" action="{{ url_for('payments.delete_payment') }}">
                        <input type="hidden" name="payment_id" id="paymentId">
                        <button type="submit" class="btn btn-danger">Eliminar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>


    

<script>
    const toggleButton = document.getElementById('toggleOrder');
    const orderInput = document.getElementById('orderInput');
    
    function openDeletePaymentModal(paymentId) {
        // Configura el ID del pago en el modal
        document.getElementById('paymentId').value = paymentId;

        // Muestra el modal
        const modal = new bootstrap.Modal(document.getElementById('deletePaymentModal'));
        modal.show();
    }


    function goToPage(pageNumber) {
        const pageInput = document.getElementById('page');
        
        pageInput.value = pageNumber;
        document.forms[0].submit();
    }


    function resetPage() {
        window.location.href = "{{ url_for('team_dashboard.order') }}";
    }

    function validateDateRange() {
        const startDate = document.getElementById("start_date").value;
        const endDate = document.getElementById("end_date").value;

        if (startDate && endDate && startDate > endDate) {
            alert("La fecha de inicio debe ser menor o igual a la fecha de fin.");
            return false;
        }
        return true;
    }
    
</script>
<script>
    function updateEndDateMin() {
        const startDate = document.getElementById("start_date").value;
        const endDateInput = document.getElementById("end_date");
        
        if (startDate) {
            endDateInput.min = startDate;

            // Si la fecha actual en el campo end_date es menor que el mínimo, limpiarlo
            if (endDateInput.value && endDateInput.value < startDate) {
                endDateInput.value = '';
            }
        } else {
            // Si start_date está vacío, eliminar el mínimo de end_date
            endDateInput.min = '';
        }

    }

    function updateStartDateMax() {
        const endDate = document.getElementById("end_date").value;
        const startDateInput = document.getElementById("start_date");

        if (endDate) {
            startDateInput.max = endDate;

            // Si la fecha actual en el campo start_date es mayor que el máximo, limpiarlo
            if (startDateInput.value && startDateInput.value > endDate) {
                startDateInput.value = '';
            }
        } else {
            // Si end_date está vacío, eliminar el máximo de start_date
            startDateInput.max = '';
        }
    }
    

</script>



{% endblock %}

{% block volver %}
<br>
    <a class="btn btn-danger" href="{{ url_for('auth.home') }}" >◄ Volver</a>
{% endblock %}

admin/src/web/templates/payments/show.html
{% extends "templates_base/layout.html" %}

{% block title %} Detalle del Pago {% endblock %}
{% block navbar%}
    {% include "templates_base/navbar.html" %}
{% endblock %}
{% block content %}
    <h2>Detalle del Pago</h2>
    <div class="card">
        <div class="card-body">
            {% if employee %}
                <p class="card-text"><strong>Beneficiario:</strong> {{ employee.name }} {{ employee.last_name }} DNI: {{ employee.dni }}</p>
            {% endif %}
            <p class="card-text"><strong>Monto:</strong>$ {{ payment.amount }} </p>
            <p class="card-text"><strong>Fecha de Pago:</strong> {{ payment.payment_date.strftime('%d-%m-%Y') }}</p>
            <p class="card-text"><strong>Tipo de Pago:</strong> {{ payment.payment_type }}</p>
            <p class="card-text"><strong>Descripción:</strong> {{ payment.description or 'Sin descripción' }}</p>
            <input type="hidden" name="payment_id" value="{{ payment.id }}">
            <div class="row" style="justify-content: center">
                <div class="col text-center">
                    <a class="btn btn-warning" href="{{ url_for('payments.edit_payment', payment_id=payment.id) }}">Editar Pago</a>
                    
                   
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block volver %}
    <br>
    <a class="btn btn-danger" href="{{ url_for('payments.dashboard') }}" >◄ Volver</a>
    
{% endblock %}