admin/src/web/controllers/charges.py
from typing import Dict, List

from flask import Blueprint, flash, redirect, render_template, request, url_for

from src.core import charges, riders
from src.core.charges import order_and_filter_charges, validate_filter_params
from src.core.riders.rider import Rider
from src.core.team import get_active_employees, get_employee
from src.web.handlers.auth import login_required, permission_required
from src.web.handlers.exceptions import ChargeNotFoundException
from src.web.validators.charges_validations import validate_charge_params
from src.core.charges.charge import Charge


bp = Blueprint("charges", __name__, url_prefix="/cobros")


@bp.get("/index")
@bp.get("/index/<int:page>")
@login_required
@permission_required("charge_index")
def index_charges(page: int = 1):
    """
    Muestra la página principal de cobros con filtros y paginación.
    """
    params = request.args
    messages: List[str] = validate_filter_params(params)
    if len(messages) > 0:
        for error in messages:
            flash(error, "error")
        return redirect(url_for("charges.index_charges", _external=True))

    order = params.get("order", "desc")
    payment_method = params.get("payment_method", "")
    start_date = params.get("start_date", "")
    end_date = params.get("end_date", "")
    receiver_first_name = params.get("receiver_name", "")
    receiver_last_name = params.get("receiver_last_name", "")
    rider_id = params.get("rider_id", "")

    charges_list, pagination = order_and_filter_charges(
        page=page,
        order=order,
        payment_method=payment_method.upper() if payment_method else None,
        start_date=start_date,
        end_date=end_date,
        receiver_first_name=receiver_first_name if receiver_first_name else "",
        receiver_last_name=receiver_last_name if receiver_last_name else "",
        rider_id=rider_id if rider_id else None,
    )

    next_page = (
        url_for("charges.index_charges", page=pagination.next_num, **params)
        if pagination.has_next
        else None
    )

    prev_page = (
        url_for("charges.index_charges", page=pagination.prev_num, **params)
        if pagination.has_prev
        else None
    )
    riders_list = riders.get_riders_in_list()

    return render_template(
        "charges/index.html",
        charges=charges_list,
        pagination=pagination,
        order=order,
        start_date=start_date,
        end_date=end_date,
        payment_method=payment_method,
        receiver_name=receiver_first_name,
        receiver_last_name=receiver_last_name,
        rider_id=rider_id,
        riders=riders_list,
        next_page=next_page,
        prev_page=prev_page
    )


@bp.get("/create")
@login_required
@permission_required("charge_create")
def new_charge():
    """
    Muestra el formulario para crear un nuevo cobro.
    """
    employees = get_active_employees()
    riders_list = riders.get_riders_in_list()

    return render_template(
        "charges/create_edit.html",
        employees=employees,
        riders=riders_list,
        params=dict(),
    )


@bp.post("/create")
@login_required
@permission_required("charge_create")
def create_charge():
    """
    Crea un nuevo cobro en la base de datos.
    """
    params = request.form
    messages: List[str] = validate_charge_params(params)
    if len(messages) > 0:
        for error in messages:
            flash(error, "error")
        employees = get_active_employees()
        riders_list = (
            riders.get_riders_in_list()
        )
        return render_template(
            "charges/create_edit.html",
            employees=employees,
            riders=riders_list,
            params=params,
        )

    charges.create_charge(params)
    flash("Cobro creado exitosamente", "success")

    return redirect(url_for("charges.index_charges"))


@bp.get("/cobro/<int:id>/edit")
@login_required
@permission_required("charge_update")
def edit_charge(id: int): 
    """
    Muestra el formulario para editar un cobro existente.
    """
    charge: Charge = charges.get_charge_by_id(id)
    employees = get_active_employees()
    riders_list = riders.get_riders_in_list()
    rider: Rider = riders.get_rider_by_id(int(charge.rider_id))
    debt = "yes" if rider.has_debt else "no"
    params: Dict[str, str] = {
        "rider_id": rider.id,
        "charge_date": charge.charge_date,
        "payment_method": charge.payment_method,
        "amount": charge.amount,
        "debt": debt,
        "receiver_id": charge.receiver_id,
        "observations": charge.observations,
    }
    return render_template(
        "charges/create_edit.html",
        cobro=charge,
        employees=employees,
        riders=riders_list,
        params=params,
    )


@bp.post("/cobro/<int:id>/edit")
@login_required
@permission_required("charge_update")
def update_charge(id):
    """
    Actualiza un cobro existente en la base de datos.
    """
    params = request.form

    params_copy = params.copy().to_dict()
    params_copy["payment_method"] = params.get("payment_method", "").upper()
    messages: List[str] = validate_charge_params(params_copy)
    if len(messages) > 0:
        for error in messages:
            flash(error, "error")
        return redirect(url_for("charges.index_charges"))

    charges.update_charge(id, params_copy)

    flash("Se actualizó el cobro correctamente", "success")

    return redirect(url_for("charges.index_charges"))


@bp.post("/charges/<int:id>/delete")
@login_required
@permission_required("charge_destroy")
def delete_charge(id):
    """
    Elimina un cobro existente de la base de datos.
    """
    try:
        charges.delete_charge_by_id(id)
    except ChargeNotFoundException:
        flash("No se pudo eliminar el cobro", "error")
        return redirect(url_for("auth.home"))

    flash("Cobro eliminado correctamente", "success")

    return redirect(url_for("charges.index_charges"))


@bp.get("/charges/<int:id>")
@login_required
@permission_required("charge_show")
def show_charge(id):
    """
    Muestra los detalles de un cobro específico.
    """
    try:
        charge = charges.get_charge_by_id(id)
        rider = riders.get_rider_by_id(charge.rider_id)
        receiver = get_employee(charge.receiver_id)
        return render_template(
            "charges/show.html", charge=charge, rider=rider, receiver=receiver
        )
    except ChargeNotFoundException:
        flash("Cobro no encontrado", "error")

        return redirect(url_for("charges.index_charges"))

admin/src/web/templates/charges/create_edit.html
{% extends "templates_base/layout.html" %}

{% block title %} Registrar un cobro {% endblock %}

{% block navbar %}
    {% include "templates_base/navbar.html" %}
{% endblock %}

{% block content %}
    <h2>
        {% if not cobro %}
            Registrar un nuevo cobro
        {% else %}
            Editar cobro
        {% endif %}
    </h2>
    <form method="POST" action="{{ url_for('charges.update_charge', id=cobro.id) if cobro else url_for('charges.create_charge') }}">
        <p class="text-muted">* Todos los campos con un (*) son obligatorios</p>

        <div class="mb-3">
            <label for="rider_id" class="form-label">Jinete/Amazona (*)</label>
            <select class="form-control" id="rider_id" name="rider_id" required>
                <option value="" {% if params.get('rider_id', '') == '' %}selected{% endif %} disabled>Selecciones un Jinete/amazona</option>
                {% for rider in riders %}
                    <option value="{{ rider.id }}" {% if params.get('rider_id', '')|int == rider.id %}selected{% endif %}>
                        {{ rider.name }} {{ rider.last_name }} - DNI: {{ rider.dni }}
                    </option>
                {% endfor %}
            </select>
        </div>

        <div class="mb-3">
            <label for="charge_date" class="form-label">Fecha del Cobro (*)</label>
            <input type="date" class="form-control" id="charge_date" 
            name="charge_date" required
            value="{{ params.get('charge_date', '') }}">
        </div>

        <div class="mb-3">
            <label for="payment_method" class="form-label">Medio de Cobro (*)</label>
            <select class="form-control" id="payment_method" name="payment_method" required>
                <option value="" {% if params.get('payment_method', '') == '' %}selected{% endif %} disabled>Seleccione un medio de cobro</option>
                <option value="EFECTIVO" {% if params.get('payment_method') == 'EFECTIVO' %}selected{% endif %}>Efectivo</option>
                <option value="TARJETA_CREDITO" {% if params.get('payment_method') == 'TARJETA_CREDITO' %}selected{% endif %}>Tarjeta de Crédito</option>
                <option value="TARJETA_DEBITO" {% if params.get('payment_method') == 'TARJETA_DEBITO' %}selected{% endif %}>Tarjeta de Débito</option>
            </select>
        </div>

        <div class="mb-3">
            <label for="amount" class="form-label">Monto (*)</label>
            <input type="text" class="form-control" id="amount"
                   name="amount" value="{{ params.get('amount', '') }}" required
                   />
            <small class="form-text text-muted">
                Use un punto (.) para separar los centavos. Ejemplo: 123.45
            </small>
        </div>

        <div class="mb-3">
            <label class="form-label">Deudor (*)</label>
            <div class="custom_radio">
                <label>
                    <input type="radio" name="debt" id="debt_yes" value="yes"
                    {% if params.get('debt', '') == 'yes' %}checked{% endif %}
                    required/>
                    <span>Si</span>
                </label>
                <label>
                    <input type="radio" name="debt" id="debt_no"value="no" required 
                    {% if params.get('debt', '') == 'no' %}checked{% endif %}/>
                    <span>No</span>
                </label>
               
                
            </div>
        </div>
        

        <div class="mb-3">
            <label for="receiver_id" class="form-label">Recibido por (*)</label>
            <select class="form-control" id="receiver_id" name="receiver_id" required>
                <option value="" {% if params.get('receiver_id', '') == '' %} selected {% endif %}>Seleccione un empleado</option>
                {% for employee in employees %}
                    <option value="{{ employee.id }}" {% if params.get('receiver_id', '')|int == employee.id %}selected{% endif %}>
                        {{ employee.name }} {{ employee.last_name }} - DNI: {{ employee.dni }}
                    </option>
                {% endfor %}
                </ul>
            
            </select>
        </div>

        <div class="mb-3">
            <label for="notes" class="form-label">Observaciones (opcional)</label>
            <textarea class="form-control" id="notes" name="observations">{{ params.get('observations', '') }}</textarea>
        </div>
        <div class="row">
            <div class="col text-end">
                <button type="submit" class="btn btn-primary">{{ 'Actualizar' if cobro else 'Registrar' }}</button>
            </div>
            
        </div>
        
    </form>
<script>
    document.getElementById('amount').addEventListener('input', function (e) {
        const value = e.target.value;
    
        // Expresión regular para validar números con una sola coma
        const isValid = /^[0-9]*.?[0-9]{0,2}$/.test(value);
    
        if (!isValid) {
            // Si el valor no es válido, elimina el último carácter ingresado
            e.target.value = value.slice(0, -1);
        }
    });
</script>
<script>
    const today = new Date().toISOString().split('T')[0];
    
    document.getElementById('charge_date').setAttribute('max', today);
</script>
{% endblock %}

{% block volver %}
<br>
    <a class="btn btn-danger" href="{{ url_for('charges.index_charges') }}" >◄ Volver</a>
{% endblock %}

admin/src/web/templates/charges/index.html
{% extends "templates_base/layout.html" %}

{% block title %}Listado de Cobros{% endblock %}

{% block navbar %}
    {% include "templates_base/navbar.html" %}
{% endblock %}

{% block content %}
    <h2>Cobros de jinetes/amazonas</h2>
    <form id="filtros" action="{{ url_for('charges.index_charges') }}" method="GET">
        <div class="row" style="justify-content: center;">
            <div class="col">
                <label for="start_date" class="form-label">Fecha inicio</label>
                <input type="date" class="form-control" id="start_date" name="start_date" value="{{ start_date }}">
            </div>
            <div class="col">
                <label for="end_date" class="form-label">Fecha fin</label>
                <input type="date" class="form-control" id="end_date" name="end_date" value="{{ end_date }}">
            </div>
            <div class="col">
                <label for="payment_method" class="form-label">Medio de pago</label>
                <select class="form-control" id="payment_method" name="payment_method">
                    <option value="">Todos</option>
                    <option value="EFECTIVO" {% if payment_method == 'EFECTIVO' %}selected{% endif %}>Efectivo</option>
                    <option value="TARJETA_CREDITO" {% if payment_method == 'TARJETA_CREDITO' %}selected{% endif %}>Tarjeta de Crédito</option>
                    <option value="TARJETA_DEBITO" {% if payment_method == 'TARJETA_DEBITO' %}selected{% endif %}>Tarjeta de Débito</option>
                </select>
            </div>
            
            
        </div>
        <div class="row" style="justify-content: center;">
            <div class="col">
                <label for="receiver_name" class="form-label">Nombre de quién recibe</label>
                <input type="text" class="form-control" id="receiver_name" name="receiver_name" value="{{ receiver_first_name if receiver_first_name != None else '' }}">
            </div>
            <div class="col">
                <label for="receiver_last_name" class="form-label">Apellido de quién recibe</label>
                <input type="text" class="form-control" id="receiver_last_name" name="receiver_last_name" value="{{ receiver_last_name if receiver_last_name != None else '' }}">
            </div>
            <div class="col">
                <label for="rider_id" class="form-label">Jinete/Amazona</label>
                <select class="form-control" id="rider_id" name="rider_id">
                    <option value="">Todos</option>
                    {% for rider in riders %}
                        <option value="{{ rider.id }}" {% if rider.id == rider_id|int %}selected{% endif %}>
                            {{ rider.name }} {{ rider.last_name }} - DNI: {{ rider.dni }}
                        </option>
                    {% endfor %}
                </select>
            </div>
            <div class="col">
                <label class="form-label">Ordenar por:</label>
                <select class="form-control" id="order" name="order">
                    <option value="" {% if order == '' %} selected {% endif %}>---</option>
                    <option value="asc" {% if order == 'asc' %} selected {% endif %}> Más viejos </option>
                    <option value="desc" {% if order == 'desc' %} selected {% endif %}>Más recientes</option>
                </select>
                
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col">
                <div class="text-end">
                    <a class="btn btn-secondary me-2" href="{{ url_for('charges.index_charges') }}">Limpiar Filtros</a>
                    <button type="submit" class="btn btn-primary" href="{{ url_for('charges.index_charges') }}">Filtrar</button>
                </div>
            </div>
        </div>
    </form>
    
    <div class="row mt-4">
        {% for charge in charges %}
            <div class="col-md-4 mb-3">
                <div class="card h-100">
                    <div class="card-body">
                        <!-- Título con nombre del jinete -->
                        <h5 class="card-title">{{ charge.rider.name }} {{ charge.rider.last_name }}</h5>
                        <!-- Detalles del cobro -->
                        <p class="card-text">
                            <strong>Fecha de pago:</strong> {{ charge.formatted_charge_date() }}<br>
                            <strong>Monto:</strong> ${{ charge.amount }}<br>
                            <strong>Medio de pago:</strong> {{ charge.payment_method.value.replace('_', ' ').title() }}<br>
                            <strong>Recibido por:</strong> {{ charge.employee.name.title() }} {{ charge.employee.last_name.title()}}
                        </p>
                        <!-- Botones dentro de un contenedor con espacio entre ellos -->
                        <div class="d-flex justify-content-center" style="gap: 3px;">
                            <!-- Botón Ver detalles -->
                            <a class="btn btn-info" href="{{ url_for('charges.show_charge', id=charge.id) }}">Ver Detalles</a>
                            
                            <!-- Botón Editar -->
                            <a class="btn btn-warning" href="{{ url_for('charges.edit_charge', id=charge.id) }}">Editar</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% if charges|length == 0 %}
            <div class="col-12 text-center my-4">
                <div class="alert alert-warning py-4">
                    <h5>No se encontraron resultados</h5>
                    <p class="mb-0">No se encontraron cobros registrados con esos criterios.</p>
                </div>
            </div>
        {% endif %}
    </div>
    {% if charges|length != 0 %}
        <nav aria-label="Page navigation" class="mt-4">
            <ul class="pagination justify-content-center">
                {% if pagination.has_prev %}
                <li class="page-item">
                    <a class="page-link" href="{{ prev_page }}" aria-label="Anterior">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}
                <li class="page-item disabled"><a class="page-link" href="#">Página {{ pagination.page }} de {{ pagination.pages }}</a></li>
                {% if pagination.has_next %}
                <li class="page-item">
                    <a class="page-link" href="{{ next_page }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% endblock %}


{% block volver %}
<br>
    <a class="btn btn-danger" href="{{ url_for('auth.home') }}">◄ Volver</a>
{% endblock %}

admin/src/web/templates/charges/show.html
{% extends "templates_base/layout.html" %}

{% block title %} Detalle del Cobro {% endblock %}
{% block navbar%}
    {% include "templates_base/navbar.html" %}
{% endblock %}
{% block content %}
    <h2>Detalle del Cobro</h2>
    <div class="card">
        <div class="card-body">
            
            <p class="card-text"><strong>Jinete/Amazona:</strong> {{ rider.name }} {{ rider.last_name }}</p>
            <p class="card-text"><strong>Fecha del Pago:</strong> {{ charge.formatted_charge_date() }}</p>
            <p class="card-text"><strong>Medio de Pago:</strong> {{ charge.payment_method.value.replace('_', ' ').title() }}</p>
            <p class="card-text"><strong>Monto:</strong> ${{ charge.amount }}</p>
            <p class="card-text"><strong>Recibido por:</strong> {{ receiver.name }} {{ receiver.last_name }}</p>
            <p class="card-text"><strong>Observaciones:</strong> {{ charge.observations }}</p>
            <p class="card-text"><strong>Deudor:</strong> {{ 'Sí' if rider.has_debt else 'No' }}</p>
            <input type="hidden" name="charge_id" value="{{ charge.id }}">
        </div>
    </div>

    <div class="row" style="justify-content: center; margin-top: 20px;">
        <div class="col text-center">
            <a class="btn btn-warning" href="{{ url_for('charges.edit_charge', id=charge.id) }}">Editar Cobro</a>
            <button class="btn btn-danger" onclick="setChargeId({{ charge.id }})" data-bs-toggle="modal" data-bs-target="#deleteChargeModal">Eliminar Cobro</button>
        </div>
    </div>

    <!-- Modal de confirmación -->
    <div class="modal fade" id="deleteChargeModal" tabindex="-1" aria-labelledby="deleteChargeModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteChargeModalLabel">Confirmar eliminación</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Cerrar"></button>
                </div>
                <div class="modal-body">
                    ¿Está seguro de que desea eliminar este cobro? Esta acción es <strong>irreversible</strong>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <button id="confirmDeleteButton" type="button" class="btn btn-danger">Eliminar cobro</button>
                </div>
            </div>
        </div>
    </div>
    


<script>
    let chargeIdToDelete = null;

    // Establece el ID del cobro a eliminar
    function setChargeId(chargeId) {
        chargeIdToDelete = chargeId;
    }

    // Agrega un evento al botón de confirmación del modal
    document.getElementById('confirmDeleteButton').addEventListener('click', function () {
        if (chargeIdToDelete) {
            // Obtener la URL base generada por Jinja con un marcador de posición
            let urlTemplate = "{{ url_for('charges.delete_charge', id=1234567890) }}";
            
            // Reemplazar el marcador de posición con el ID dinámico
            let actionUrl = urlTemplate.replace('1234567890', chargeIdToDelete);

            // Crear un formulario dinámico
            const form = document.createElement('form');
            form.method = 'POST';
            form.action = actionUrl;

            // Agregar el formulario al documento y enviarlo
            document.body.appendChild(form);
            form.submit();
        }
    });

</script>
{% endblock %}
{% block volver %}
<br>
    <a class="btn btn-danger" href="{{ url_for('charges.index_charges') }}" >◄ Volver</a>
{% endblock %}